/**
 * TestFly Java Codegen Service
 * Translates Playwright actions, selector events, and DOM checks into TestFly Java 21 test code.
 */

export interface RecordedAction {
    type: 'navigate' | 'click' | 'type' | 'select' | 'assert_title' | 'assert_url' | 'assert_visible' | 'assert_text';
    selector?: string;
    role?: string;
    roleName?: string;
    text?: string;
    value?: string;
    expected?: string;
}

export interface CodegenOptions {
    className: string;
    packageName: string;
    framework: 'testng' | 'junit5' | 'page_object';
    baseUrl?: string;
}

export class CodegenService {
    /**
     * Generate TestFly Java code from recorded actions.
     */
    public static generate(actions: RecordedAction[], options: CodegenOptions): string {
        switch (options.framework) {
            case 'page_object':
                return this.generatePageObject(actions, options);
            case 'junit5':
                return this.generateJUnit5Test(actions, options);
            case 'testng':
            default:
                return this.generateTestNGTest(actions, options);
        }
    }

    private static generateLocatorExpression(action: RecordedAction): string {
        if (action.role && action.roleName) {
            return `getByRole(Role.${action.role.toUpperCase()}, new RoleOptions().setName("${action.roleName}"))`;
        }
        if (action.role) {
            return `getByRole(Role.${action.role.toUpperCase()})`;
        }
        if (action.text) {
            return `getByText("${action.text}")`;
        }
        if (action.selector) {
            if (action.selector.startsWith('//') || action.selector.startsWith('(//')) {
                return `find(By.xpath("${action.selector}"))`;
            }
            if (action.selector.startsWith('#')) {
                return `find(By.id("${action.selector.slice(1)}"))`;
            }
            return `find(By.cssSelector("${action.selector}"))`;
        }
        return `find(By.cssSelector("*"))`;
    }

    private static generateStep(action: RecordedAction): string {
        switch (action.type) {
            case 'navigate':
                return action.value ? `open("${action.value}");` : `open();`;
            case 'click':
                return `${this.generateLocatorExpression(action)}.click();`;
            case 'type':
                return `${this.generateLocatorExpression(action)}.type("${action.value || ''}");`;
            case 'select':
                return `${this.generateLocatorExpression(action)}.selectOption("${action.value || ''}");`;
            case 'assert_title':
                return `assertThatPage().hasTitle("${action.expected || ''}");`;
            case 'assert_url':
                return `assertThatPage().hasUrl("${action.expected || ''}");`;
            case 'assert_visible':
                return `assertThat(${this.generateLocatorExpression(action)}).isVisible();`;
            case 'assert_text':
                return `assertThat(${this.generateLocatorExpression(action)}).hasText("${action.expected || ''}");`;
            default:
                return `// Unsupported action: ${JSON.stringify(action)}`;
        }
    }

    private static generateTestNGTest(actions: RecordedAction[], options: CodegenOptions): string {
        const steps = actions.map(a => `        ${this.generateStep(a)}`).join('\n');
        return `package ${options.packageName};

import io.testfly.locator.Role;
import io.testfly.locator.RoleOptions;
import io.testfly.test.BaseTest;
import org.openqa.selenium.By;
import org.testng.annotations.Test;

/**
 * Auto-generated by TestFly Studio.
 */
public class ${options.className} extends BaseTest {

    @Test
    public void executeRecordedFlow() {
${steps}
    }
}
`;
    }

    private static generateJUnit5Test(actions: RecordedAction[], options: CodegenOptions): string {
        const steps = actions.map(a => `        ${this.generateStep(a)}`).join('\n');
        return `package ${options.packageName};

import io.testfly.junit5.BaseJUnit5Test;
import io.testfly.locator.Role;
import io.testfly.locator.RoleOptions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

/**
 * Auto-generated by TestFly Studio.
 */
public class ${options.className} extends BaseJUnit5Test {

    @Test
    @DisplayName("Recorded user flow")
    public void executeRecordedFlow() {
${steps}
    }
}
`;
    }

    private static generatePageObject(actions: RecordedAction[], options: CodegenOptions): string {
        const pageName = options.className.endsWith('Page') ? options.className : `${options.className}Page`;
        const testName = options.className.endsWith('Test') ? options.className : `${options.className}Test`;

        const steps = actions.map(a => `        ${this.generateStep(a)}`).join('\n');

        return `// ================= ${pageName}.java =================
package ${options.packageName};

import io.testfly.locator.Locator;
import io.testfly.locator.Role;
import io.testfly.locator.RoleOptions;
import io.testfly.test.BasePage;
import org.openqa.selenium.By;

public class ${pageName} extends BasePage {

    public void runFlow() {
${steps}
    }
}

// ================= ${testName}.java =================
package ${options.packageName};

import io.testfly.test.BaseTest;
import org.testng.annotations.Test;

public class ${testName} extends BaseTest {

    @Test
    public void testPageFlow() {
        ${pageName} page = new ${pageName}();
        page.runFlow();
    }
}
`;
    }
}
