import * as fs from 'fs';
import * as path from 'path';
import { CodegenService, RecordedAction } from './codegenService';
import { ActionCacheService } from './actionCacheService';
import { RemediationService } from './remediationService';
import { SharderService } from './sharderService';
import { DEFAULT_POM_XML, DEFAULT_TESTFLY_YML, DEFAULT_SMOKE_TEST } from './constants';

export interface McpToolDefinition {
    name: string;
    description: string;
    inputSchema: Record<string, any>;
}

export const TESTFLY_BRIDGE_TOOLS: McpToolDefinition[] = [
    {
        name: 'generate_testfly_code',
        description: 'Generate production-ready TestFly Java 21 test code (BaseTest, BasePage, getByRole, assertThat) from Playwright interactions or DOM inspection.',
        inputSchema: {
            type: 'object',
            properties: {
                className: { type: 'string', default: 'RecordedFlowTest', description: 'Name of the generated Java class' },
                packageName: { type: 'string', default: 'io.testfly.examples.testng', description: 'Java package name' },
                framework: { type: 'string', enum: ['testng', 'junit5', 'page_object'], default: 'testng', description: 'Test framework target' },
                actions: {
                    type: 'array',
                    description: 'List of recorded actions (navigate, click, type, select, assert_title, assert_visible, assert_text)',
                    items: {
                        type: 'object',
                        properties: {
                            type: { type: 'string' },
                            selector: { type: 'string' },
                            role: { type: 'string' },
                            roleName: { type: 'string' },
                            text: { type: 'string' },
                            value: { type: 'string' },
                            expected: { type: 'string' }
                        },
                        required: ['type']
                    }
                }
            },
            required: ['actions']
        }
    },
    {
        name: 'inspect_action_cache',
        description: 'Read and inspect autonomous act("Goal") action plans frozen in .testfly/action-cache.json for 0ms replay.',
        inputSchema: {
            type: 'object',
            properties: {
                workspaceRoot: { type: 'string', description: 'Root directory of the TestFly project' }
            }
        }
    },
    {
        name: 'manage_action_cache',
        description: 'Invalidate or clear cached action plans in .testfly/action-cache.json so the AI re-compiles them upon next test execution.',
        inputSchema: {
            type: 'object',
            properties: {
                workspaceRoot: { type: 'string', description: 'Root directory of the TestFly project' },
                action: { type: 'string', enum: ['invalidate', 'clear_all'], default: 'invalidate' },
                goal: { type: 'string', description: 'Specific goal name to invalidate (required when action=invalidate)' }
            },
            required: ['action']
        }
    },
    {
        name: 'list_remediations',
        description: 'List pending AI self-healing git diff .patch files generated by AiHealingEngine in target/remediations/.',
        inputSchema: {
            type: 'object',
            properties: {
                workspaceRoot: { type: 'string', description: 'Root directory of the TestFly project' }
            }
        }
    },
    {
        name: 'apply_remediation_patch',
        description: 'Apply a self-healing git diff patch from target/remediations/ directly to the Java test source code.',
        inputSchema: {
            type: 'object',
            properties: {
                workspaceRoot: { type: 'string', description: 'Root directory of the TestFly project' },
                patchFilePath: { type: 'string', description: 'Full path to the .patch file' }
            },
            required: ['patchFilePath']
        }
    },
    {
        name: 'init_testfly_project',
        description: 'Scaffold a modern TestFly 1.0.6 Java 21 test automation project with pom.xml, testfly.yml, and sample test.',
        inputSchema: {
            type: 'object',
            properties: {
                directory: { type: 'string', description: 'Target directory for project scaffolding' }
            },
            required: ['directory']
        }
    },
    {
        name: 'calculate_shards',
        description: 'Calculate optimal CI parallel test partitions using the Longest Processing Time (LPT) bin-packing algorithm.',
        inputSchema: {
            type: 'object',
            properties: {
                totalNodes: { type: 'number', default: 4 },
                targetNodeIndex: { type: 'number', default: 0 },
                items: {
                    type: 'array',
                    items: {
                        type: 'object',
                        properties: {
                            className: { type: 'string' },
                            durationMs: { type: 'number' }
                        },
                        required: ['className', 'durationMs']
                    }
                }
            },
            required: ['totalNodes', 'targetNodeIndex', 'items']
        }
    }
];

export class McpBridgeHandler {
    public static async handleToolCall(name: string, args: Record<string, any>): Promise<any> {
        const root = args.workspaceRoot || process.cwd();

        switch (name) {
            case 'generate_testfly_code': {
                const code = CodegenService.generate(args.actions as RecordedAction[], {
                    className: args.className || 'RecordedFlowTest',
                    packageName: args.packageName || 'io.testfly.examples.testng',
                    framework: args.framework || 'testng'
                });
                return { content: [{ type: 'text', text: code }] };
            }

            case 'inspect_action_cache': {
                const plans = ActionCacheService.readCache(root);
                return {
                    content: [{
                        type: 'text',
                        text: JSON.stringify({ count: plans.length, plans }, null, 2)
                    }]
                };
            }

            case 'manage_action_cache': {
                if (args.action === 'clear_all') {
                    const ok = ActionCacheService.clearAll(root);
                    return { content: [{ type: 'text', text: ok ? 'Cleared all action plans.' : 'Failed to clear.' }] };
                }
                const ok = ActionCacheService.invalidateGoal(root, args.goal || '');
                return { content: [{ type: 'text', text: ok ? `Invalidated goal: ${args.goal}` : 'Failed to invalidate.' }] };
            }

            case 'list_remediations': {
                const patches = RemediationService.listPatches(root);
                return {
                    content: [{
                        type: 'text',
                        text: JSON.stringify({ count: patches.length, patches }, null, 2)
                    }]
                };
            }

            case 'apply_remediation_patch': {
                const res = await RemediationService.applyPatch(root, args.patchFilePath);
                return { content: [{ type: 'text', text: res.message }] };
            }

            case 'init_testfly_project': {
                const dir = args.directory;
                fs.mkdirSync(dir, { recursive: true });
                fs.writeFileSync(path.join(dir, 'pom.xml'), DEFAULT_POM_XML, 'utf8');
                fs.writeFileSync(path.join(dir, 'testfly.yml'), DEFAULT_TESTFLY_YML, 'utf8');
                const testDir = path.join(dir, 'src', 'test', 'java', 'io', 'testfly', 'examples', 'testng');
                fs.mkdirSync(testDir, { recursive: true });
                fs.writeFileSync(path.join(testDir, 'SmokeTest.java'), DEFAULT_SMOKE_TEST, 'utf8');
                return { content: [{ type: 'text', text: `Scaffolded TestFly 1.0.6 Java 21 project at ${dir}` }] };
            }

            case 'calculate_shards': {
                const res = SharderService.shard(args.items, args.totalNodes, args.targetNodeIndex);
                return { content: [{ type: 'text', text: JSON.stringify(res, null, 2) }] };
            }

            default:
                throw new Error(`Unknown tool: ${name}`);
        }
    }
}
